chore(CI): Simplify how namespace is handled in PR Preview Workflow

diff --git a/.github/workflows/pr.yaml b/.github/workflows/pr.yaml
--- a/.github/workflows/pr.yaml
+++ b/.github/workflows/pr.yaml
@@ -13,6 +13,7 @@ env:
   DOMAIN_NAME: "pr-${{ github.event.number }}.website-preview.rm3l.org"
   ODO_DISABLE_TELEMETRY: "true"
   PODMAN_CMD: "docker"
+  NAMESPACE: "rm3l-org-pr-${{ github.event.number }}"
   PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
   PR_NUMBER: ${{ github.event.number }}
 
@@ -43,13 +44,13 @@ jobs:
 
       - name: Create and set namespace
         run: |
-          if odo list namespaces | grep "pr-${PR_NUMBER}"; then
-            echo "Namespace pr-${PR_NUMBER} already exists."
+          if odo list namespaces | grep "$NAMESPACE"; then
+            echo "Namespace $NAMESPACE already exists."
           else
-            echo "Namespace pr-${PR_NUMBER} *not* found => creating it."
-            odo create namespace "pr-${PR_NUMBER}"
+            echo "Namespace $NAMESPACE *not* found => creating it."
+            odo create namespace "$NAMESPACE"
           fi
-          odo set namespace "pr-${PR_NUMBER}"
+          odo set namespace "$NAMESPACE"
 
       - name: Login to Docker Hub
         uses: docker/login-action@v2
@@ -71,7 +72,7 @@ jobs:
             --var DEPLOY_CERTMANAGER_CLUSTERISSUER="${{ secrets.CERTMANAGER_CLUSTERISSUER_PREVIEW_URLS }}" \
             --var DEPLOY_INGRESS_CLASS=traefik \
             --var DOMAIN_NAME \
-            --var RESOURCE_NAME="rm3l-org-v2-pr-${PR_NUMBER}"
+            --var RESOURCE_NAME="rm3l-org-pr-${PR_NUMBER}"
 
       - name: Test access
         run: |
@@ -129,7 +130,7 @@ jobs:
         run: |
           mkdir -p /tmp && cd /tmp
           odo delete component \
-            --namespace "pr-${PR_NUMBER}" \
+            --namespace "$NAMESPACE" \
             --name "rm3l-org-pr-${PR_NUMBER}" \
             --force \
             --wait
@@ -137,8 +138,8 @@ jobs:
       - name: Delete namespace
         if: ${{ always() }}
         run: |
-          odo delete namespace "pr-${PR_NUMBER}" \
+          odo delete namespace "$NAMESPACE" \
             --wait \
             --force \
-          || echo "Could not delete namespace pr-${PR_NUMBER} - please delete it manually!"
+          || echo "Could not delete namespace $NAMESPACE - please delete it manually!"
 
